version: '3'
services:

  db:
    image: mysql:5.7.24
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-conf/mysql/:/temp
      - dbdata:/var/lib/mysql/
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
volumes:
  dbdata:
    driver: local

# version: '3.3'

# services:

#   db:
#     image: mysql/mysql-server:5.7
#     container_name: "${DOCKER_PREFIX}-db"
#     restart: unless-stopped
#     # volumes:
#     #   - "database:/var/lib/mysql"
#     ports:
#       - 3306:3306
#     environment:
#       - "MYSQL_ROOT_HOST=%"
#       - "MYSQL_ROOT_PASSWORD=${DOCKER_PASSWORD}"
#       - "MYSQL_DATABASE=${DOCKER_DATABASE}"
#       - "MYSQL_USER=${DOCKER_USER}"
#       - "MYSQL_PASSWORD=${DOCKER_PASSWORD}"
#     command: [
#       "--character-set-server=utf8mb4",
#       "--collation-server=utf8mb4_general_ci",
#       "--default-storage-engine=innodb",
#       "--innodb-file-per-table",
#       "--explicit_defaults_for_timestamp=1",
#       "--default-time-zone=+00.00"
#     ]
# # volumes:
# #   database: